title:        Copyleft
description:  'Hacker, Programmer'
baseUrl: /copyleft
url:          http://vinitkumar.me/copyleft
version:      1.0.0
author:
  name:       'John Doe'
  email:      'johndoe@me.com'

# owner/author information
owner:
  name:           John Doe
  avatar:         <your avatar>
  email:      johndoe@me.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: johndoe
  github: gotchacode
  stackexchange: 
  # For Google Authorship https://plus.google.com/authorship
  google_plus:  +gotchacode
profile_image: 'https://avatars0.githubusercontent.com/u/537678?v=3&s=460'
# Analytics and webmaster tools stuff goes here
google_analytics: 
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
gems: [jekyll-paginate]
markdown:     kramdown
permalink:    pretty
highlighter:  rouge
paginate:     5
